version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - gces-networks
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
    ports:
      - "27017:27017"
    networks:
      - gces-networks
    volumes:
      - mongodb-data:/data/db

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - "5000:5000"
    networks:
      - gces-networks
    volumes:
      - metabase:/metabase-data
    depends_on:
      - mongo
      
      
volumes:
  mongodb-data:
  metabase:
networks:
  gces-networks:
    driver: bridge