name: Continuous Deployment

on:
  release:
    branches: [ main ]
env:
  PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}    
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
    - uses: actions/checkout@v3
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Build 
      run: poetry build 

    - name: Publish to PyPI
      run:  poetry publish --username __token__ --password $PYPI_TOKEN
